"""Pridėtas discount_id į Order modelį

Revision ID: 0727dddedb16
Revises: 453f3c7ea208
Create Date: 2025-07-30 22:15:15.902990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0727dddedb16'
down_revision = '453f3c7ea208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'discount', ['discount_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('discount_id')

    # ### end Alembic commands ###
