"""Increase password_hash length to 512

Revision ID: 7439859d3121
Revises: 721de5d8ccff
Create Date: 2025-07-29 17:13:29.958147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7439859d3121'
down_revision = '721de5d8ccff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
