"""Pridėti laukai email confirmation prie user modelio

Revision ID: 8730db84a99b
Revises: fba968f280ce
Create Date: 2025-07-28 17:40:42.514778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8730db84a99b'
down_revision = 'fba968f280ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_confirmation_token', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_confirmation_token')
        batch_op.drop_column('email_confirmed_at')
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###
