"""Add loyalty and min_purchase to Discount

Revision ID: c60f3ec03f3b
Revises: cb9267dd7304
Create Date: 2025-08-03 11:58:59.632309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60f3ec03f3b'
down_revision = 'cb9267dd7304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_purchase', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('loyalty_min_orders', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loyalty_min_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('loyalty_period_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.drop_column('loyalty_period_days')
        batch_op.drop_column('loyalty_min_amount')
        batch_op.drop_column('loyalty_min_orders')
        batch_op.drop_column('min_purchase')

    # ### end Alembic commands ###
